repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "google"]  # Use Google profile to match yapf

-   repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
    -   id: yapf
        args: ["--style", "google"]  # Use Google style to match isort

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - --fail-under=9.0
          - --disable=import-error
          - --ignore-paths=^tests/.*$
          - --score=yes
          - --load-plugins=pylint.extensions.docparams
          - --max-line-length=120
        require_serial: true
