repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: ["--profile", "google"]

-   repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
    -   id: yapf
        args: ["--style", "google", "--recursive", "--in-place"]

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        # Only fail on actual errors (E), not warnings (W) or conventions (C)
        args: ["--fail-on=E"]
        pass_filenames: true
        exclude: ^tests/
        verbose: true
        # Keep hooks running on pre-commit
        stages: [pre-commit]

    -   id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        args: ["--no-header", "--no-summary", "-xvs"]
        stages: [pre-commit, pre-push]
        verbose: true
        always_run: true
        fail_fast: false
