from enum import Enum


class LocationType(str, Enum):
    POSTAL_CODE = "POSTAL_CODE"
    POINT_OF_INTEREST = "POINT_OF_INTEREST"
    ADMINISTRATIVE_AREA = "ADMINISTRATIVE_AREA"
    STREET = "STREET"
    STATE = 'STATE'
    LOCALITY = "LOCALITY"
    CITY_POSTAL_CODE = "CITY_POSTAL_CODE"
    CITY_NO_POSTAL_CODE = "CITY_NO_POSTAL_CODE"
    COUNTRY = "COUNTRY"
    ANY = "ANY"